//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NldtLession10Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NldtAccount
    {
        public int NldtID { get; set; }
        public string NldtName { get; set; }
        public string NldtPassword { get; set; }
        public string NldtFullName { get; set; }
        public string NldtEmail { get; set; }
        public string NldtPhone { get; set; }
        public Nullable<bool> NldtActive { get; set; }
    }
}
